---
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - run: npm ci --ignore-scripts
      - run: npm run lint
      - run: npm run build
